apiVersion: v1
kind: Service
metadata:
  name: idp-service
  labels:
    app: seatbooking-app
    name: idp-service
spec:
  selector:
    app: seatbooking-app
    name: idp-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-deployment
  labels:
    app: seatbooking-app
    name: idp-deployment
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: idp-pod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: idp-pod
      labels:
        app: seatbooking-app
        name: idp-pod
    spec:
      containers:
        - name: idp-pod
          image: dhamodaran/idp_api:latest
          resources:
            requests:
              cpu: 500m
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: 192.168.65.2
