apiVersion: v1
kind: Service
metadata:
  name: idp-service
  labels:
    app: seatbooking-app
    name: idp-service
spec:
  selector:
    app: seatbooking-app
    name: idp-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      #nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-deployment
  labels:
    app: seatbooking-app
    name: idp-deployment
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: idp-pod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: idp-pod
      labels:
        app: seatbooking-app
        name: idp-pod
    spec:
      containers:
        - name: idp-container
          image: dhamodaran/idp_api:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 3000
          env:
            - name: CHECK_DB
              value: yess
            - name: DB_HOST
              value: 192.168.65.2
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: idp_db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: idp_db_password
            - name: DB_SCHEME
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: idp_db_schema 