apiVersion: v1
kind: Service
metadata:
  name: seatbooking-service
  labels:
    app: seatbooking-app
    name: seatbooking-service
spec:
  selector:
    app: seatbooking-app
    name: seatbookingpod
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatbooking-deployment
  labels:
    app: seatbooking-app
    name: seatbooking-deployment
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: seatbookingpod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: seatbookingpod
      labels:
        app: seatbooking-app
        name: seatbookingpod
    spec:
      containers:
        - name: seatbookingpod
          image: dhamodaran/seatbooking_api:latest
          ports:
            - containerPort: 3000
